COMMUNITY_FEEDS:
  # BOTVRIJ.EU feed
  # Feed can be with context as: http://www.botvrij.eu/data/ioclist.ip-dst
  # or without (with `raw` postfix): http://www.botvrij.eu/data/ioclist.ip-dst.raw
  # botvrijIpDst: http://www.botvrij.eu/data/ioclist.ip-dst.raw
  #botvrijDomain: http://www.botvrij.eu/data/ioclist.domain.raw
  #botvrijUrl: http://www.botvrij.eu/data/ioclist.url.raw
  #botvrijFilename: http://www.botvrij.eu/data/ioclist.filename.raw
  #botvrijMD5: http://www.botvrij.eu/data/ioclist.md5.raw
  #botvrijSHA1: http://www.botvrij.eu/data/ioclist.sha1.raw
  #botvrijSHA256: http://www.botvrij.eu/data/ioclist.sha256.raw
  #botvrijEmailSrc: http://www.botvrij.eu/data/ioclist.email-src.raw
  #botvrijRegkey: http://www.botvrij.eu/data/ioclist.regkey.raw

  # SANS feeds
  SANSHighSuspiciousDomains: https://isc.sans.edu/feeds/suspiciousdomains_High.txt
  SANSMedSuspiciousDomains: https://isc.sans.edu/feeds/suspiciousdomains_Medium.txt
  SANSLowSuspiciousDomains: https://isc.sans.edu/feeds/suspiciousdomains_Low.txt
  SANSTorExitNodes: https://isc.sans.edu/feeds/topips.txt

VENDOR_FEEDS:
  OTX:
    OTX_API_KEY: 0cd94635a2655f3455978567d7d352339cbe710712cda594034a496982b11561
  XFORCE:
    #XFORCE_URL:
    #XFORCE_API:

MISP:
  X_ISAC_MISP:
    MISP_NAME: "X-ISAC MISP"
    URL: https://misp.x-isac.org
    API_KEY: DOnJuKMn9sJ8yKPTSaOQwpFZRjgaWL3ECNC37pq3
  LIMEO_MISP:
    MISP_NAME: "Limeo MISP"
    URL: https://misp.limeo.org
    API_KEY: mU1kG0oVIO9Y606GFBdiHbGqYPPJrK5YrxLEYZ4R
